extend = "target/rust-driver-makefile.toml"

[config]
load_script = '''
#!@rust
//! ```cargo
//! [dependencies]
//! wdk-build = "0.4"
//! ```
#![allow(unused_doc_comments)]

wdk_build::cargo_make::load_rust_driver_makefile()?
'''

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clippy]
install_crate = "rust-clippy"
command = "cargo"
args = [
    "clippy",
    "--all-targets",
    "--all-features",
    "--no-deps",
    "--",
    "-D", "warnings",
    "-D", "clippy::all",
    "-D", "clippy::pedantic",
    "-A", "clippy::missing_panics_doc",
    "-A", "missing_docs",
    "-A", "clippy::missing_safety_doc",
    "-A", "clippy::missing_errors_doc",
]

[tasks.check]
dependencies = [
    "format",
    "clippy",
]

[tasks.build-driver]
dependencies = [
    "check",
    "package-driver-flow",
]